### ISSUE TITLE
Explore generating MSs without CASAPY

### ISSUE THREAD

**Issue by SpheMakh** [SpheMakh/simms#13]
It may be a time consuming exercise, but worth looking into nonetheless.  This is what would be required:
1) Convert ENU -> ITRF  (Simple)
2) ITRF -> UVW (Simple)
3) Create MS table from scratch, take into account all subtables and columns (This would be the time consuming part) 
4) Automatically determining the start times is also not trivial, but must be possible since CASA has done it. 

1,3,4 will require pyrap

**Comment by o-smirnov** [comment]
But isn't this exactly what makems tries to do (albeit not perfectly...)? Might it not be easier to fix makems?

As for #4, pyrap.measures is your (awkward but powerful) friend.

**Comment by SpheMakh** [comment]
I really have to befriend pyrap.measures, I can't ignore this for much longer. I agree that is what makems tries to do, but I think it can be much simpler in python (using pyrap).  Do you know if its possible to get access to the `simulator` tool in CASA, in the same way as the `table, measures, quanta` tools; that would be the simplest solution.

**Comment by SpheMakh** [comment]
Will reconsider this when I have time.
