### ISSUE TITLE
Simulating scans with specified dates and start times?

### ISSUE THREAD

**Issue by prinapatel** [SpheMakh/simms#16]
Hi there,

I am wondering are you able to create an MS where you can specify the start time and date for each scan in an observation?

Prina

**Comment by SpheMakh** [comment]
Done. You can now set the `-date`  option multiple times. Each `-date` represents the start of a new scan. 
Example
```
simms -T kat-7 -st 4 -sl 2 ../simms/observatories/KAT7_ANTENNAS -date "2014/12/31/14:54:30" -date "2014/12/31/16:54:30"
```
gives 2 2hr scans starting at the specified times. and, 

Example
```
simms -T kat-7 -st 4 -sl 1,3 ../simms/observatories/KAT7_ANTENNAS -date "2014/12/31/14:54:30" -date "2014/12/31/16:54:30"
```
gives you a 1hr and a 3hr scan starting at the specified times.
