### ISSUE TITLE
A regular spacing between scans

### ISSUE THREAD

**Issue by TariqBlecher** [SpheMakh/simms#23]
A possible extra feature:
To observe the same source over many scans each of which are separated by a constant spacing in time.

**Comment by SpheMakh** [comment]
Done, please run more tests and come back to me :)

**Comment by SpheMakh** [comment]
The option is `-slg/--scan-lag`

**Comment by SpheMakh** [comment]
@TariqBlecher is the fix working for you?

**Comment by TariqBlecher** [comment]
Yes it is thanks
