### ISSUE TITLE
How to create a VLA MS for a given configuration

### ISSUE THREAD

**Issue by modhurita** [SpheMakh/simms#5]
1. Copy the antenna table for your desired VLA configuration from elwood: /home/makhathini/vla-pos
1. Suppose you want to create an MS for VLA in C configuration. Run this command:

> \<path to simms\>/simms.py -T VLA -n VLAC.MS -t ascii -dt 600 -st 8 -ih -4 -nc 8 -df 24e+6 -f0 1.330e9 -dir J2000,1.49488453rad,0.8700817rad vlac.itrf.txt

Pinging @atemkeng as he is working with VLA-C MSs.

**Comment by SpheMakh** [comment]
This info is now in README
