### ISSUE TITLE
Can't read FLAG_CATEGORY column 

### ISSUE THREAD

**Issue by modhurita** [SpheMakh/simms#6]
There is something wrong with the FLAG_CATEGORY column; it seems to exist in the simulated MS, but I can't open it:

>In [53]: t.getcol('FLAG_CATEGORY')

>RuntimeError                              Traceback (most recent call last)
<ipython-input-53-86eb4bae8075> in <module>()
----> 1 t.getcol('FLAG_CATEGORY')

>/usr/lib/python2.7/dist-packages/pyrap/tables/table.pyc in getcol(self, columnname, startrow, nrow, rowincr)
    854 #                i = inx*
    855 #        except:
--> 856         return self._getcol (columnname, startrow, nrow, rowincr)
    857 
    858     def getvarcol (self, columnname, startrow=0, nrow=-1, rowincr=1):

>RuntimeError: Table DataManager error: Invalid operation: TSM: no array in row 0 of column FLAG_CATEGORY in /home/mitra/SimTest/VLA-C.MS/table.f8

**Comment by SpheMakh** [comment]
I doubt this something I can fix here. The problem probably lies deep in CASA.
